owner/urls.py
from django.urls import path,include
from . import views

app_name="owner"
urlpatterns = [  
    path('', views.index,name='home'),
    path('project', views.projects,name='projects'),
    path('project/plc', views.plcRules,name='plcRules'),
    path('project/plc/create', views.plcRulesCreate,name='plcRules_create'),
    path('project/plc/<int:id>/edit', views.plcRulesEdit,name='plcRules_edit'),
    path('project/<int:id>/', views.projectView, name='project_view'),
    path('project/<int:id>/edit', views.projectEdit, name='project_edit'),
    path('project/<int:id>/delete', views.projectDelete, name='project_delete'),
    path('project/<int:proid>/section/<int:id>', views.sectionView, name='section_view'),
    path('project/<int:proid>/section/<int:id>/edit', views.sectionEdit, name='section_edit'),
    path('project/<int:proid>/section/<int:id>/delete', views.sectionDelete, name='section_delete'),
    path('property/<int:id>/', views.propertyView,name='property_view'),
    path('property/<int:id>/edit', views.propertyEdit,name='property_edit'),
    path('property/<int:id>/delete', views.propertyDelete,name='property_delete'),
    path('customers', views.customerListView, name='customers'),
    path('customers/add', views.createCutomer, name='customer_create'),
    path('customers/<int:id>/edit', views.customerEdit, name='customer_edit'),
    path('customers/<int:id>/', views.customerView, name='customer_view'),
    path('associates', views.associates, name='associates'),
    path('associates/add', views.associateCreate, name='associate_view'),
    path('associates/edit/<int:id>', views.associateEdit, name='associate_edit'),
    path('associates/edit/<int:id>/photo', views.associateEditPhoto, name='associate_edit_photo'),
    path('associates/suspend/<int:id>', views.associateSuspend, name='associate_suspend'),
    path('associates/activate/<int:id>', views.associateActivate, name='associate_activate'),
    path('associates/hold-payments/<int:id>', views.associateHoldPayments, name='associate_HoldPayments'),
    path('associates/release-payments/<int:id>', views.associateReleasePayments, name='associate_releasePayments'),
    path('associates/terminate/<int:id>', views.associateTerminate, name='associate_terminate'),
    path('associates/<int:id>', views.associateView, name='associate_view'),
    path('sales/status/',views.propertyByStatus,name='property_status'),
    path('sales/status/list/<slug:slug>',views.propertyListByStatus,name='property_list_status'),
    path('sales/pos/',views.sales,name='pos_list'),
    path('sales/pos/<int:id>',views.pointofSales,name='pos'),
    path('sales/salesbook/',views.salesBook,name='sales_book'),
    path('sales/receipt/<int:id>',views.bookingReceipt,name='booking_receipt'),
    path('finance/booking-deposit/<int:id>', views.depositBooking, name='booking_deposit'),
    path('finance/login-amount', views.loginAmount, name='login_amount'),
    path('finance/deposit-login-amount/<int:id>', views.depositLoginAmount, name='deposit_login_amount'),
    path('finance/deposit-emi/<int:id>', views.depositEmi, name='deposit_emi'),
    path('finance/receipt/<int:id>',views.paymentReceipt,name='payment_receipt'),
    path('finance/payouts', views.payoutList, name='payout_list'),
    path('finance/payouts/advance', views.payoutAdvance, name='payout_advance'),
    path('finance/payout-payments/<int:id>', views.payoutPayment, name='payout_payments'),
    path('finance/release-earnings/<int:id>', views.releaseEarnings, name='release_earning'),
    path('finance/rewards', views.rewards, name='rewards'),
    path('finance/other-expences/<int:id>', views.otherExpences, name='other_expences'),
    path('finance/redeem-rewards/<int:id>', views.redeemRewards, name='redeem_rewards'),
    path('reports/sales-report',views.salesReport, name='sales_report'),
    path('reports/buisness-report',views.buisnessReport, name='buisness_report'),
    path('reports/emi-report',views.emiReport, name='emi_report'),
    path('profile',views.salesBook, name='profile_edit'),
    path('policy/payout/', views.payoutRules, name='payout_rules'),
    path('policy/payout/create', views.payoutRulesCreate, name='payout_rules_create'),
    path('policy/payout/<int:id>/edit', views.payoutRulesEdit, name='payout_rules_edit'),
    path('policy/rewards/', views.rewardRules, name='reward_rules'),     
    path('policy/rewards/create', views.rewardRulesCreate, name='reward_rules_create'),     
    path('policy/rewards/<int:id>/edit', views.rewardRulesEdit, name='reward_rules_edit'),     
    
    ]

    #project/id/edit
    

realEstate2/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings 
from django.conf.urls.static import static 


urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('webapp.urls')),
    path('associate/' , include('associate.urls')),
    path('customers/' , include('customers.urls')),
    path('owner/' , include('owner.urls')),
    path('projects/' , include('projects.urls')),
    path('api/customer/' , include('customers.api.urls')),
    path('api/config/' , include('config.api.urls')),
    #path('api/project/' , include('projects.api.urls')),
    path('user/' , include('user.urls'))
    #path('report/' , include('reports.urls'))
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path,include
from . import views

app_name="user"
urlpatterns = [  
    
    path('login', views.login ,name='login'),
   # path('register', views.register ,name='register'),
   # path('forgot-password', views.forgotPassword ,name='forgot'),
    path('logout', views.logout ,name='logout'),
    path('password-change',views.passwordChange ,name='passwordChange'),
    path('profile-edit',views.profileEdit ,name='profile_edit'),
    path('profile-view',views.profileView ,name='profile_view'),
    path('user-list',views.userList,name='user_list'),
    path('add-user',views.addUser,name='add_user'),
    path('activate-user/<int:id>',views.userActivate,name='activate_user'),
    path('deactivate-user/<int:id>',views.userDeactivate,name='deactivate_user'),

     
    ]

    #project/id/edit
    

reports/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from projects.models import Project,Property,Transaction,EMI
from associate.models import Associate


class Sale(models.Model):
    amount=models.IntegerField()
    property_ref=models.ForeignKey(Property,on_delete=models.SET_NULL,blank=True, null=True)
    associate_ref=models.ForeignKey(Associate,on_delete=models.SET_NULL,blank=True, null=True)
    status=models.BooleanField(default=False)
    createdAt= models.DateTimeField(auto_now_add=True)
    #status is to check whether it has been calncelled or not
    #year = property(_get_year) #EDIT

#use celery to generate monthly sale report summary of sale table
class MonthlySales(models.Model):
    MONTH = (             
        ('JAN', 'January'),
        ('FEB', 'February'),
        ('MAR', 'March'),
        ('APR', 'April'),
        ('MAY', 'May'),
        ('JUN', 'June'),
        ('JUL', 'July'),
        ('AUG', 'August'),
        ('SEP', 'September'),
        ('OCT', 'October'),
        ('NOV', 'November'),
        ('DEC', 'December'),        
    )
    amount=models.IntegerField()
    associate_ref=models.ForeignKey(Associate,on_delete=models.SET_NULL,blank=True, null=True)
    sale_month=models.IntegerField()
    sale_year=models.IntegerField()
    status=models.BooleanField(default=False)
    createdAt= models.DateTimeField(auto_now_add=True)
    last_updated= models.DateTimeField(auto_now=True)

#amount needs to calculated using payout table
#this table need to updated when customer pays
class PayoutRule(models.Model):
    sale_start_amount=models.IntegerField()
    sale_end_amount=models.IntegerField()
    payout=models.IntegerField()
    reward=models.IntegerField()
    is_monthly=models.BooleanField(default=False)

#after evrery calculations this table will be updated if associate fulfils rule. till 
class PayoutLifetime(models.Model):
    payout_rule=models.ForeignKey(PayoutRule,on_delete=models.SET_NULL,blank=True, null=True)
    associate_ref=models.ForeignKey(Associate,on_delete=models.SET_NULL,blank=True, null=True)
    createdAt= models.DateTimeField(auto_now_add=True)

class PayoutMonthly(models.Model):
    payout_rule=models.ForeignKey(PayoutRule,on_delete=models.SET_NULL,blank=True, null=True)
    associate_ref=models.ForeignKey(Associate,on_delete=models.SET_NULL,blank=True, null=True)
    createdAt= models.DateTimeField(auto_now_add=True)

# to show the earnings add absolute percentage 
class SelfEarning(models.Model):
    amount=models.DecimalField(max_digits=19, decimal_places=2)
    associate_ref=models.ForeignKey(Associate,on_delete=models.SET_NULL,blank=True, null=True)
    status=models.BooleanField(default=False)
    payout_rule=models.ForeignKey(PayoutRule,on_delete=models.SET_NULL,blank=True, null=True)
    payout_rule_value=models.IntegerField(blank=True, null=True)
    createdAt= models.DateTimeField(auto_now_add=True)
    cus_tx=models.ForeignKey(Transaction,on_delete=models.SET_NULL,blank=True, null=True)
    is_onhold=models.BooleanField(default=False)
#status shows payment staus of this earning
class TeamEarning(models.Model):
    amount=models.DecimalField(max_digits=19, decimal_places=2)
    associate_ref=models.ForeignKey(Associate,on_delete=models.SET_NULL,blank=True, null=True)
    status=models.BooleanField(default=False)
    payout=models.DecimalField(max_digits=5, decimal_places=2)
    createdAt= models.DateTimeField(auto_now_add=True)
    cus_tx=models.ForeignKey(Transaction,on_delete=models.SET_NULL,blank=True, null=True)
    is_onhold=models.BooleanField(default=False)
#add team earning rule
#for amount recived payment by the associate
class AssociateTransaction(models.Model):
    METHOD = (             
        ('C', 'Cash Payment'),
        ('Q', 'Cheque'),
        ('N', 'NEFT'),
        ('D', 'Bank Draft'),
        ('A', 'Added balance'),
                
    )
    associate_ref=models.ForeignKey(Associate,on_delete=models.SET_NULL,blank=True, null=True)
    pay_method=models.CharField(max_length=1, choices=METHOD)
    date=models.DateTimeField(blank=True,auto_now=False, auto_now_add=True)
    reference_no=models.CharField(blank=True,null=True, max_length=50)
    credit=models.DecimalField( max_digits=20, decimal_places=2,blank=True,null=True)
    debit=models.DecimalField( max_digits=20, decimal_places=2,blank=True,null=True)
    balance=models.DecimalField( max_digits=20, decimal_places=2,blank=True,null=True)
    description=models.TextField(blank=True,null=True)

class DeductionsRule(models.Model):
    value=models.IntegerField()
    reason=models.CharField(max_length=50)
    #add fields credit, debit(with name advance) balance
class OtherExpences(models.Model):
    METHOD = (             
        ('C', 'Cash Payment'),
        ('Q', 'Cheque'),
        ('N', 'NEFT'),
        ('D', 'Bank Draft'),
        ('A', 'Added balance'),                
    )
    EXPENCE_TYPE_CHOICES = (
      (1, 'Marketing'),
      (2, 'Office Expence'),
      (3, 'Employee Salary'),
      (4, 'Tour'),
      (5, 'Visit'),
      (6, 'Other Expences'),      
    )
    expence_type = models.PositiveSmallIntegerField(choices=EXPENCE_TYPE_CHOICES,blank=True, null=True)
    pay_method=models.CharField(max_length=1, choices=METHOD)
    date=models.DateTimeField(blank=True,auto_now=False, auto_now_add=True)
    reference_no=models.CharField(blank=True,null=True, max_length=50)
    amount=models.DecimalField( max_digits=20, decimal_places=2,blank=True,null=True)
    description=models.TextField(blank=True,null=True)
    #add fields credit, debit(with name advance) balance
      
#in lakhs
class RewardsRule(models.Model):
    sale_amount=models.IntegerField()
    reward=models.CharField(max_length=50)
class RewardEarning(models.Model):     
    reward_rule=models.ForeignKey(RewardsRule,on_delete=models.SET_NULL, blank=True, null=True)
    associate_ref=models.ForeignKey(Associate,on_delete=models.SET_NULL, blank=True, null=True)
    createdAt= models.DateTimeField(auto_now_add=True)
    status=models.BooleanField(default=True)     

class RewardPassbook(models.Model):
    createdAt= models.DateTimeField(auto_now_add=True)
    description=models.CharField(max_length=100)
    sale_amount_balance=models.DecimalField(max_digits=10, decimal_places=2)
    associate_ref=models.ForeignKey(Associate,on_delete=models.SET_NULL, blank=True, null=True)
    reward_value=models.IntegerField(default=5)
    debit_amount=models.DecimalField(max_digits=10, decimal_places=2)
    credit_amount=models.DecimalField(max_digits=10, decimal_places=2)
    reward_balance=models.DecimalField(max_digits=10, decimal_places=2)

 

reports/forms.py
from django import forms
from .models import Sale, AssociateTransaction,OtherExpences,RewardsRule,PayoutRule
from projects.models import PriceRule

class SaleForm(forms.ModelForm):
    class Meta:
        model = Sale
        fields = ['amount',
                  'property_ref',
                  'associate_ref',
                  'status'
                  ]


class BookingForm(forms.Form):
    total_amount = forms.DecimalField(
        max_digits=6, decimal_places=2, required=False)
    booking_amount = forms.DecimalField(
        max_digits=6, decimal_places=2, required=False)
    payment_mode = forms.CharField(max_length=1, required=True)
    emi_plan = forms.IntegerField(required=True)
    reference_no = forms.CharField(max_length=100, required=True)
class RedeemForm(forms.Form):
    id=forms.IntegerField(required=True)


class AssociateTransactionForm(forms.ModelForm):

    class Meta:
        model = AssociateTransaction
        fields = ['associate_ref',
                  'pay_method',
                  'reference_no',
                  'debit',
                  'description'
                  ]


class OtherExpencesForm(forms.ModelForm):    
    class Meta:
        model = OtherExpences
        fields = ("__all__")

class RewardsRuleForm(forms.ModelForm):
    class Meta:
        model = RewardsRule
        fields = ("__all__")

class PriceRuleForm(forms.ModelForm):
    class Meta:
        model = PriceRule
        fields = ("__all__")

class PayoutRuleForm(forms.ModelForm):
    class Meta:
        model = PayoutRule
        fields = ("__all__")

reports/views.py
from django.shortcuts import render

# Create your views here.

reports/templates/reports/companyPolicy/form.html
{% extends "base.html" %}
{% block title %}
{{heading}}
{% endblock title %}
<!-- heading  -->
{% block heading %}
{{heading}}
{% endblock %}


<!-- desktop menu -->
{% block desk-sidebar%}
{% include 'sidebar.html' %}
{% endblock %}

{% load static %}
<!-- Main Conent -->
{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {% load crispy_forms_tags %}
    <table>
            {{form.as_table}}
    </table>
  
    <button class="btn btn" style="background-color: #2979ff">Submit</button>

</form>
{% endblock %}

reports/templates/reports/companyPolicy/payout_rules.html
{% extends "base.html" %}
{% block title %}
Payout Rules
{% endblock title %}
<!-- heading  -->
{% block heading %}
Payout Rules
{% endblock %}


<!-- desktop menu -->
{% block desk-sidebar%}
{% include 'sidebar.html' %}
{% endblock %}

{% load static %}
<!-- Main Conent -->
{% block content %}
<div class="row">
    <div class="col-12">
        <a href="{% url 'owner:payout_rules_create' %}" class="btn btn-primary">Add New Rule</a>
        <div class="card-body">
                <table id="myTable" class="flex-table table">

                <thead class="thead-dark">
                    <tr>
                        <th>Serial No</th>
                        <th>Sales Range </th>

                        <th>Payout level</th>
                        <th>Reward</th>
                        <th>Calculation Basis</th>
                        
                        {% if user.user_type == 1 %}
                        <th>Action</th>
                            
                        {% endif %}
                            
                    </tr>
                </thead>
                <tbody>



                    {% for rule in rules %}
                    <tr>
                        <td>
                            {{rule.id}}
                        </td>
                        <td>&#8377; {{rule.sale_start_amount}} -

                            {{rule.sale_end_amount}} Lakhs</td>
                        <td>{{rule.payout}}%</td>
                        <td>{{rule.reward}}%</td>
                        <td>

                            {% if rule.is_monthly %}
                            <span style="color: navy">
                                Monthly Sales
                            </span>

                            {% else %}
                            <span style="color: brown">
                                Lifetime Sales
                            </span>

                            {% endif %}


                        </td>
                        
                        {% if user.user_type == 1 %}
                            <td>
                                <a href="{% url 'owner:payout_rules_edit' id=rule.id %}" class="btn btn-sm btn-warning">EDIT</a>
                            </td>
                        {% endif %}
                            
                    </tr>
                    {% endfor %}

                </tbody>
            </table>
        </div>
    </div>
    {% endblock %}

reports/templates/reports/companyPolicy/reward_rules.html
{% extends "base.html" %}
{% block title %}
Rewards Rules
{% endblock title %}
<!-- heading  -->
{% block heading %}
Rewards Rules
{% endblock %}
<!-- desktop menu -->
{% block desk-sidebar%}
{% include 'sidebar.html' %}
{% endblock %}

{% load static %}
<!-- Main Conent -->
{% block content %}
<div class="row">
    <div class="col-12">
            <a href="{% url 'owner:reward_rules_create' %}" class="btn btn-primary">Add New Rule</a>

        <div class="card-body">
                <table id="myTable" class="flex-table table">

                <thead class="thead-dark">
                    <tr>
                        <th>Serial No</th>
                        <th>Total Sales </th>                        
                        <th>Reward</th>  
                        {% if user.user_type == 1 %}
                        <th>Action</th>
                            
                        {% endif %}                      
                    </tr>
                </thead>
                <tbody>



                    {% for rule in rules %}
                    <tr>
                        <td>{{rule.id}}</td>
                        <td>&#8377; {{rule.sale_amount}} Lakhs</td>                       
                        <td>{{rule.reward}}</td>
                        {% if user.user_type == 1 %}
                            <td>
                                <a href="{% url 'owner:reward_rules_edit' id=rule.id %}" class="btn btn-sm btn-warning">EDIT</a>
                            </td>
                        {% endif %}
                            
                    </tr>
                    {% endfor %}

                </tbody>
            </table>
            <script>
                    $(document).ready(function () {
                        $('#myTable').DataTable(
                            {
                                "order": [[0, "desc"]]
                            }
                        );
                    });
                </script>
        </div>
    </div>
    {% endblock %}