associate/urls.py
from django.urls import path,include
from . import views

app_name="associate"
urlpatterns = [  
    path('', views.index,name='home'),
   # path('register', views.register, name='register'), 
    path('project', views.projects,name='projects'),
    path('project/<int:id>/', views.projectView, name='project_view'),
    path('project/<int:proid>/section/<int:id>', views.sectionView, name='section_view'), 
    path('property/<int:id>/', views.propertyView,name='property_view'),
    path('project/plc', views.plcRules,name='plcRules'),
    path('customers', views.customerListView, name='customers'),
    path('customers/<int:id>/', views.customerView, name='customer_view'),
    path('rewards', views.rewardView, name='rewards'),
    path('upline', views.uplineView, name='upline'), 
    path('downlines', views.downlines, name='downlines'),
    path('downlines/<int:id>', views.downlineView, name='downline_view'),
    path('downlines/add', views.downlineCreateView, name='downline_add'),    
    path('buisness-summary', views.buisnessSummary, name='buisness_summary'),
    path('team-buisness', views.teamBuisness, name='team_buisness'),
    path('leader-rewards', views.leaderRewards, name='leader_rewards'),
    path('my-earnings', views.myEarnings, name='my_earnings'),
    path('earnings-forcast', views.earningForcast, name='earning_forcast'),
    path('passbook', views.passbook, name='passbook'),
    path('profile', views.myProfile, name='profile'),
    path('profile/edit', views.profileEdit, name='profile_edit'), 
    path('changepwd', views.changePwd, name='changepwd'),              
    ]

    #project/id/edit
    

owner/urls.py
from django.urls import path,include
from . import views

app_name="owner"
urlpatterns = [  
    path('', views.index,name='home'),
    path('project', views.projects,name='projects'),
    path('project/plc', views.plcRules,name='plcRules'),
    path('project/plc/create', views.plcRulesCreate,name='plcRules_create'),
    path('project/plc/<int:id>/edit', views.plcRulesEdit,name='plcRules_edit'),
    path('project/<int:id>/', views.projectView, name='project_view'),
    path('project/<int:id>/edit', views.projectEdit, name='project_edit'),
    path('project/<int:id>/delete', views.projectDelete, name='project_delete'),
    path('project/<int:proid>/section/<int:id>', views.sectionView, name='section_view'),
    path('project/<int:proid>/section/<int:id>/edit', views.sectionEdit, name='section_edit'),
    path('project/<int:proid>/section/<int:id>/delete', views.sectionDelete, name='section_delete'),
    path('property/<int:id>/', views.propertyView,name='property_view'),
    path('property/<int:id>/edit', views.propertyEdit,name='property_edit'),
    path('property/<int:id>/delete', views.propertyDelete,name='property_delete'),
    path('customers', views.customerListView, name='customers'),
    path('customers/add', views.createCutomer, name='customer_create'),
    path('customers/<int:id>/edit', views.customerEdit, name='customer_edit'),
    path('customers/<int:id>/', views.customerView, name='customer_view'),
    path('associates', views.associates, name='associates'),
    path('associates/add', views.associateCreate, name='associate_view'),
    path('associates/edit/<int:id>', views.associateEdit, name='associate_edit'),
    path('associates/edit/<int:id>/photo', views.associateEditPhoto, name='associate_edit_photo'),
    path('associates/suspend/<int:id>', views.associateSuspend, name='associate_suspend'),
    path('associates/activate/<int:id>', views.associateActivate, name='associate_activate'),
    path('associates/hold-payments/<int:id>', views.associateHoldPayments, name='associate_HoldPayments'),
    path('associates/release-payments/<int:id>', views.associateReleasePayments, name='associate_releasePayments'),
    path('associates/terminate/<int:id>', views.associateTerminate, name='associate_terminate'),
    path('associates/<int:id>', views.associateView, name='associate_view'),
    path('sales/status/',views.propertyByStatus,name='property_status'),
    path('sales/status/list/<slug:slug>',views.propertyListByStatus,name='property_list_status'),
    path('sales/pos/',views.sales,name='pos_list'),
    path('sales/pos/<int:id>',views.pointofSales,name='pos'),
    path('sales/salesbook/',views.salesBook,name='sales_book'),
    path('sales/receipt/<int:id>',views.bookingReceipt,name='booking_receipt'),
    path('finance/booking-deposit/<int:id>', views.depositBooking, name='booking_deposit'),
    path('finance/login-amount', views.loginAmount, name='login_amount'),
    path('finance/deposit-login-amount/<int:id>', views.depositLoginAmount, name='deposit_login_amount'),
    path('finance/deposit-emi/<int:id>', views.depositEmi, name='deposit_emi'),
    path('finance/receipt/<int:id>',views.paymentReceipt,name='payment_receipt'),
    path('finance/payouts', views.payoutList, name='payout_list'),
    path('finance/payouts/advance', views.payoutAdvance, name='payout_advance'),
    path('finance/payout-payments/<int:id>', views.payoutPayment, name='payout_payments'),
    path('finance/release-earnings/<int:id>', views.releaseEarnings, name='release_earning'),
    path('finance/rewards', views.rewards, name='rewards'),
    path('finance/other-expences/<int:id>', views.otherExpences, name='other_expences'),
    path('finance/redeem-rewards/<int:id>', views.redeemRewards, name='redeem_rewards'),
    path('reports/sales-report',views.salesReport, name='sales_report'),
    path('reports/buisness-report',views.buisnessReport, name='buisness_report'),
    path('reports/emi-report',views.emiReport, name='emi_report'),
    path('profile',views.salesBook, name='profile_edit'),
    path('policy/payout/', views.payoutRules, name='payout_rules'),
    path('policy/payout/create', views.payoutRulesCreate, name='payout_rules_create'),
    path('policy/payout/<int:id>/edit', views.payoutRulesEdit, name='payout_rules_edit'),
    path('policy/rewards/', views.rewardRules, name='reward_rules'),     
    path('policy/rewards/create', views.rewardRulesCreate, name='reward_rules_create'),     
    path('policy/rewards/<int:id>/edit', views.rewardRulesEdit, name='reward_rules_edit'),     
    
    ]

    #project/id/edit
    

realEstate2/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings 
from django.conf.urls.static import static 


urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('webapp.urls')),
    path('associate/' , include('associate.urls')),
    path('customers/' , include('customers.urls')),
    path('owner/' , include('owner.urls')),
    path('projects/' , include('projects.urls')),
    path('api/customer/' , include('customers.api.urls')),
    path('api/config/' , include('config.api.urls')),
    #path('api/project/' , include('projects.api.urls')),
    path('user/' , include('user.urls'))
    #path('report/' , include('reports.urls'))
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path,include
from . import views

app_name="user"
urlpatterns = [  
    
    path('login', views.login ,name='login'),
   # path('register', views.register ,name='register'),
   # path('forgot-password', views.forgotPassword ,name='forgot'),
    path('logout', views.logout ,name='logout'),
    path('password-change',views.passwordChange ,name='passwordChange'),
    path('profile-edit',views.profileEdit ,name='profile_edit'),
    path('profile-view',views.profileView ,name='profile_view'),
    path('user-list',views.userList,name='user_list'),
    path('add-user',views.addUser,name='add_user'),
    path('activate-user/<int:id>',views.userActivate,name='activate_user'),
    path('deactivate-user/<int:id>',views.userDeactivate,name='deactivate_user'),

     
    ]

    #project/id/edit
    

associate/models.py
from django.db import models
#from django.contrib.auth.models import User
from user.models import User
from django.utils import timezone
from mptt.models import MPTTModel, TreeForeignKey

class Associate(MPTTModel):
    GENDER = (             
        ('M', 'Male'),
        ('F', 'Female'),     
    )
    user=models.ForeignKey(User, on_delete=models.CASCADE,blank=True,null=True)
    title=models.CharField(max_length=5,blank=True, null=True,default='Mr')
    name= models.CharField(max_length=100)
    parent= TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')
    country_code=models.CharField(max_length=50,blank=True,null=True)   
    contact_no=models.BigIntegerField(unique=False)
    alternate_no=models.BigIntegerField(null=True, blank=True)
    email=models.EmailField(unique=False)
    address=models.CharField(max_length=100,null=True, blank=True)
    pincode=models.IntegerField(null=True, blank=True,)
    photo=models.ImageField(upload_to='images/associate/',blank=True, null=True)
    gender=models.CharField(max_length=1, choices=GENDER)
    status=models.BooleanField(default=True,blank=True, null=True)
    createdAt= models.DateTimeField(auto_now_add=True)
    date_of_birth=models.DateTimeField(auto_now=False, auto_now_add=False,null=True, blank=True)
    pan_no=models.CharField(max_length=10,blank=True, null=True)
    bank_name=models.CharField(max_length=50,blank=True, null=True)
    branch_name=models.CharField(max_length=50,blank=True, null=True)
    account_no=models.CharField(max_length=50,blank=True, null=True)
    ifsc_code=models.CharField(max_length=50,blank=True, null=True)
    is_payment_on_hold=models.BooleanField(default=False)
    class MPTTMeta:
        order_insertion_by = ['name']
# Create your models here.

associate/forms.py
from django import forms
from .models import Associate
class AssociateForm(forms.Form):
    GENDER = (             
        ('M', 'Male'),
        ('F', 'Female'),   
    )    
    title=forms.CharField(max_length=5)
    first_name= forms.CharField(max_length=100)
    last_name= forms.CharField(max_length=100)
    password= forms.CharField(max_length=50)
    photo=forms.ImageField()
    uplineID=forms.CharField(max_length=10, required=False)
    contact_no=forms.IntegerField(required=True)
    alternate_no=forms.IntegerField()
    email= forms.EmailField(required=True)
    address=forms.CharField(max_length=100)
    pincode=forms.IntegerField()
    gender=forms.ChoiceField(choices=GENDER)
    date_of_birth=forms.DateField(required=False)
    pan_no=forms.CharField(max_length=10)
    branch_name=forms.CharField(max_length=50)
    bank_name=forms.CharField(max_length=50)
    account_no=forms.CharField(max_length=50)
    ifsc_code=forms.CharField(max_length=50)
class AssociateEditForm(forms.Form):
    GENDER = (             
        ('M', 'Male'),
        ('F', 'Female'),   
    )    
    title=forms.CharField(max_length=5)
    first_name= forms.CharField(max_length=100)
    last_name= forms.CharField(max_length=100)
    photo=forms.ImageField(required=False)
    uplineID=forms.CharField(max_length=10, required=False)
    contact_no=forms.IntegerField(required=True)
    alternate_no=forms.IntegerField()
    email= forms.EmailField(required=True)
    address=forms.CharField(max_length=100)
    pincode=forms.IntegerField()
    gender=forms.ChoiceField(choices=GENDER)
    date_of_birth=forms.DateField(required=False)
    pan_no=forms.CharField(max_length=10)
    branch_name=forms.CharField(max_length=50)
    bank_name=forms.CharField(max_length=50)
    account_no=forms.CharField(max_length=50)
    ifsc_code=forms.CharField(max_length=50)

class DownlineForm(forms.ModelForm):
    class Meta:
        model= Associate
        fields= '__all__'
class UpdateForm(forms.ModelForm):
    class Meta:
        model= Associate
        fields= [
        'name',        
        'contact_no',
        'alternate_no',
        'email',
        'address',
        'photo'
        ]

associate/templates/associate/associateEdit.html
{% extends "base.html" %}
{% block title %}
Edit Associate
{% endblock title %}
<!-- heading  -->
{% block heading %}
Edit Associate
{% endblock %}
<!-- desktop menu -->
{% block desk-sidebar%}
{% include 'sidebar.html' %}
{% endblock %}
{% load static %}
<!-- Main Conent -->
{% block content %}
<style>
    input[type=number]::-webkit-inner-spin-button,
    input[type=number]::-webkit-outer-spin-button {
        -webkit-appearance: none;
        margin: 0;
    }
</style>

<div class="row">
    <div class="col-3"></div>
    <div class="col-6">


        {% load crispy_forms_tags %}
        <table>

            

                <div class="fileinput fileinput-new text-center" id="add-img" data-provides="fileinput">
                    <div class="fileinput-new thumbnail img-raised">
                        <img src="{%get_media_prefix%}{{associate.photo}}" alt="...">
                    </div>
                    <div class="fileinput-preview fileinput-exists thumbnail img-raised"></div>
                    <div>

                    </div>
                </div>
                <br>
                <form action="{% url 'owner:associate_edit_photo' id=associate.id %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <input type="file" name="photo" id="photo"/>
                    <button type="submit" class="btn btn-sm btn-rose" >Change Image</button>
                </form>
                <div id="input-container">
   
                
                </div>
                <br>
                <br>
                <form action="" method="post" id="form" enctype="multipart/form-data">
                    {% csrf_token %}
                Select Title:
                <select name="title" id="">
                    <option value="Mr">Mr</option>
                    <option value="Ms">Ms</option>
                    <option value="Mrs">Mrs</option>
                </select>
                {{form.first_name|as_crispy_field}}
                {{form.last_name|as_crispy_field}}
                {{form.gender|as_crispy_field}}
                <div class="form-group">
                    <label class="label-control">Datetime Picker</label>
                    <input type="text" id="date" onblur="change()" class="form-control datetimepicker" />
                    <input type="hidden" id='date_value' name='date_of_birth'>
                    <input type="hidden" name="password" id="pwd">
                </div>
                {{form.uplineID|as_crispy_field}}
                {{form.contact_no|as_crispy_field}}
                {{form.alternate_no|as_crispy_field}}
                {{form.email|as_crispy_field}}
                {{form.address|as_crispy_field}}
                {{form.pincode|as_crispy_field}}

                <br>

                <h4>Bank Details</h4>
                {{form.bank_name|as_crispy_field}}
                {{form.branch_name|as_crispy_field}}
                {{form.account_no|as_crispy_field}}
                {{form.pan_no|as_crispy_field}}
                {{form.ifsc_code|as_crispy_field}}
                <button class="btn btn-default" type="button" onclick="sb()"
                    style="background-color:#007bff ">Submit</button>

            </form>

        </table>
    </div>
    <div class="col-3"></div>

</div>

<script>

    function addPhoto() {
        var input = document.createElement("input");
        input.type = "file";
        input.name = "photo";
        input.id = "photo";
        
        var container = document.getElementById('input-container');
        container.appendChild(input);
        //.innerHTML=' <input type="file" name="photo" id="photo"/>'
    }
    $(function () {
        $('.datetimepicker').datetimepicker({
            icons: {
                time: "fa fa-clock-o",
                date: "fa fa-calendar",
                up: "fa fa-chevron-up",
                down: "fa fa-chevron-down",
                previous: 'fa fa-chevron-left',
                next: 'fa fa-chevron-right',
                today: 'fa fa-screenshot',
                clear: 'fa fa-trash',
                close: 'fa fa-remove'
            },
        });
    });
    var data_ref = document.getElementById('date');
    data_ref.on
    function change() {
        data_ref.addEventListener('change', getData());
    }

    function getData() {
        var data = document.getElementById('date').value
        var arr = data.substr(0, 10).split('/')
        document.getElementById('date_value').value = arr[2] + "-" + arr[0] + "-" + arr[1];
        document.getElementById('pwd').value = "pwd" + arr[1] + arr[0] + arr[2];

    }
    $(document).ready(function () {

        //document.getElementById('photo').value="{{associate.photo}}";
        document.getElementById('id_first_name').value = "{{associate.user.first_name}}";
        document.getElementById('id_last_name').value = "{{associate.user.last_name}}";
        document.getElementById('date').value = "{{associate.date_of_birth}}";
        document.getElementById('id_gender').value = "{{associate.gender}}";
        document.getElementById('id_uplineID').value = "{{associate.parent.user.username}}";
        document.getElementById('id_contact_no').value = "{{associate.contact_no}}";
        document.getElementById('id_alternate_no').value = "{{associate.alternate_no}}";
        document.getElementById('id_email').value = "{{associate.email}}";
        document.getElementById('id_address').value = "{{associate.address}}";
        document.getElementById('id_pincode').value = "{{associate.pincode}}";
        document.getElementById('id_bank_name').value = "{{associate.bank_name}}";
        document.getElementById('id_branch_name').value = "{{associate.branch_name}}";
        document.getElementById('id_account_no').value = "{{associate.account_no}}";
        document.getElementById('id_pan_no').value = "{{associate.pan_no}}";
        document.getElementById('id_ifsc_code').value = "{{associate.ifsc_code}}";


        document.getElementById('id_ifsc_code').style.textTransform = 'uppercase';
        document.getElementById('id_uplineID').style.textTransform = 'uppercase';
        document.getElementById('id_pan_no').style.textTransform = 'uppercase';
        document.getElementById('id_first_name').style.textTransform = 'capitalize';
        document.getElementById('id_last_name').style.textTransform = 'capitalize';
        document.getElementById('id_address').style.textTransform = 'capitalize';
        document.getElementById('id_bank_name').style.textTransform = 'capitalize';
        document.getElementById('id_branch_name').style.textTransform = 'capitalize';

        var pan_no = document.getElementById('id_pan_no');
        $("#form").submit(function (e) {
            //stop submitting the form to see the disabled button effect
            e.preventDefault();
        });



    });
    function sb() {

        var error = "";
        var error_count = 0;
        /*  if(document.getElementById('photo').value=="")
         {   error_count++;
             error+="\n"+("Add a Photo");
         } */
        if (document.getElementById('id_first_name').value == "") {
            error_count++;
            error += "\n" + ("Enter First Name");
        }
        if (document.getElementById('id_last_name').value == "") {
            error_count++;
            error += "\n" + ("Enter Last Name");
        }
        if (document.getElementById('date').value == ""|document.getElementById('date').value == "None") {
            error_count++;
            error += "\n" + ("Enter Date of birth");
        }
        if (document.getElementById('id_uplineID').value == "") {
            error_count++;
            error += "\n" + ("Enter Upline ID");
        }
        if (document.getElementById('id_contact_no').value == "") {
            error_count++;
            error += "\n" + ("Enter Contact no");
        }
        if (document.getElementById('id_contact_no').value != "" & document.getElementById('id_contact_no').value.length != 10) {
            error_count++;
            error += "\n" + ("Invalid Contact no");
        }
        if (document.getElementById('id_alternate_no').value != ""
            & document.getElementById('id_alternate_no').value.length != 10) {
            error_count++;
            error += "\n" + ("Invalid Alternate mobile no");
        }
        if (document.getElementById('id_alternate_no').value == "") {
            error_count++;
            error += "\n" + ("Enter Alternate Contact no");
        }
        if (document.getElementById('id_email').value == "") {
            error_count++;
            error += "\n" + ("Enter email Address");
        }
        if (document.getElementById('id_address').value == "") {
            error_count++;
            error += "\n" + ("Enter Address");
        }
        if (document.getElementById('id_pincode').value == "") {
            error_count++;
            error += "\n" + ("Enter Pin Code");
        }
        if (document.getElementById('id_pincode').value.length != 6) {
            error_count++;
            error += "\n" + ("Invalid Pin Code");
        }
        if (document.getElementById('id_bank_name').value == "") {
            error_count++;
            error += "\n" + ("Enter Bank Name");
        }
        if (document.getElementById('id_branch_name').value == "") {
            error_count++;
            error += "\n" + ("Enter Branch Name");
        }
        if (document.getElementById('id_account_no').value == "") {
            error_count++;
            error += "\n" + ("Enter Bank Account Number");
        }
        if (document.getElementById('id_pan_no').value == "") {
            error_count++;
            error += "\n" + ("Enter Pan number");
        }
        if (document.getElementById('id_pan_no').value != "") {

            var pana = document.getElementById('id_pan_no').value;
            var pan_apha = pana.substr(0, 5) + pana.charAt(9);
            var pan_num = pana.substr(5, 4)
            var letters = /^[A-Za-z]+$/;
            var number = /^[0-9]*$/;
            // error+="\n"+(pan_num.match(number));
            if ((pan_apha.match(letters) == null) | pan_num.match(number) == null | pana.length != 10) {
                error_count++;
                error += "\n" + ("Invalid Pan number");
            }

        }
        if (document.getElementById('id_ifsc_code').value == "") {
            error_count++;
            error += "\n" + ("Enter IFSC Code");
        }
        if ((document.getElementById('id_ifsc_code').value.length != 11) & (document.getElementById('id_ifsc_code').value != "")) {
            error_count++;
            error += "\n" + ("Invalid IFSC Code");
        }
        if (error_count > 0) {
            window.alert(error);
            
        }
       else if (error_count == 0) {
            console.log(error_count);
            document.getElementById('form').submit();
        }
    }
</script>





{% endblock %}

associate/templates/associate/associateList.html
{% extends "base.html" %}
{% block title %}
My associates
{% endblock title %}
<!-- heading  -->
{% block heading %}
My associates
{% endblock %}


<!-- desktop menu -->
{% block desk-sidebar%}
{% include 'sidebar.html' %}
{% endblock %}


<!-- Main Conent -->
{% block content %}

<div class="row ">
  <div class="col-lg-12">
    <table id="myTable" class="flex-table table">

      <thead>
        <tr>
          <th>AID</th>
          <th>Name</th>
          <th>Date of Joining</th>
          <th>Status</th>
          <th>Downlines</th>
          <th>Listed Customers</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        {% load mathfilters %}
        {% for associate in associate_list %}
        <tr>
          <td data-label="AID">{{associate.user.username}} </td>
          <td data-label="Associate Name">{{associate.name}}</td>

          <td data-label="Date of Joining">
            {{associate.createdAt|date}}
          </td>
          <td data-label="Status">
            {% if associate.status %}
            <div class="badge badge-success">
              <i class="fas fa-check-circle"></i>
              Active</div>
            {% else %}
            <div class="badge badge-danger">
              <i class="fas fa-times"></i>
              Suspended</div>
            {% endif %}
          </td>
          <td data-label="No of Downlines">
            <script> var count = 0;</script>
            {% for item in associate_list %}
            {% if item.parent_id == associate.id%}
            <script>count++;
            </script>
            {% endif %}
            {% endfor %}
            <script>document.write(count);</script>
          </td>
          <td data-label="Listed Customers">
            <script> count = 0;</script>
            {% for item in customers %}
            {% if item.associate_ref.id == associate.id%}
            <script>count++;
            </script>
            {% endif %}
            {% endfor %}
            <script>document.write(count);</script>
          </td>
          <td data-label="Actions">

            {% if user.user_type is not 7 %}
              <a class="btn btn-sm  btn-info" href="{% url 'owner:associate_view' id=associate.id %}">
                <i class="far fa-eye"></i>
              </a>
              {% if user.user_type == 1 or user.user_type == 2 %}
                <a class="btn btn-sm  btn-warning" href="{% url 'owner:associate_edit' id=associate.id %}">
                  <i class="far fa-edit"></i>
                </a>
                {% endif %}

                {% if user.user_type == 1 %}


                {% if associate.status %}
                <a class="btn btn-sm  btn-danger" href="{% url 'owner:associate_suspend' id=associate.id %} ">
                  <i class="fas fa-user-slash"></i>
                </a>
                {% else %}
                <a class="btn btn-sm  btn-success" href="{% url 'owner:associate_activate' id=associate.id %} ">
                  <i class="fas fa-user"></i>
                </a>

                {% endif %}
              {% endif %}
            {% endif %}
            <!-- ASSOCIATe -->
            {% if user.user_type == 7  %}
            <a class="btn btn-sm  btn-info" href="{% url 'associate:downline_view' id=associate.id %}">
                <i class="far fa-eye"></i>
              </a>
            {% endif %}
              





          </td>

        </tr>
        {% endfor %}

      </tbody>

    </table>
  </div>

</div>

<script>
  $(document).ready(function () {
    $('#myTable').DataTable({
      "pagingType": "full_numbers"
    });
  });
</script>
{% endblock %}


{% load static %}

associate/templates/associate/blank.html
{% extends "base.html" %}
{% block title %}

{% endblock title %}
<!-- heading  -->
{% block heading %}

{% endblock %}


<!-- desktop menu -->
{% block desk-sidebar%}
{% include 'sidebar.html' %}
{% endblock %}


<!-- Main Conent -->
{% block content %}
<span style="font-size: 10pt; color: red;">To filter by date:- 
        use yyyymmdd format eg: 20190712 for july 12, 2019 <br>
        To filter by month:- 
        use yyyymm format eg: 201907 for july 2019 <br>
        To filter by year:- 
        use yyyy format eg: 2019 for  2019</span>
{% endblock %}


{% load static %}

associate/templates/associate/index.html
{% extends "base.html" %}
{% block title %}
Dashboard
{% endblock title %}
<!-- heading  -->
{% block heading %}
Dashboard
{% endblock %}

<!-- desktop menu -->
{% block desk-sidebar%}
{% include 'sidebar.html' %}
{% endblock %}


<!-- Main Conent -->
{% block content %}

<!--######################################################### 
    code for notifications -->
<iframe id="myFrame" src="/default.asp" style="display:none;"></iframe>
<script>
        var array=[]
        </script>
{% if messages %}
{% for message in messages %}
     <script>
     array.push({tags:"{{message.tags}}", msg:"{{message}}"});
     </script>
{% endfor %}
{% endif %}
<script>
document.getElementById("myFrame").addEventListener("load", myFunction);

function myFunction() {
  //document.getElementById("demo").innerHTML = "Iframe is loaded.";
 
  array.forEach(element => {
    if (element.tags=='error') {
        element.tags='danger';
    }
    showNotification(element.msg,element.tags);
    console.log(element) 
  });
  
}
    
function showNotification(msg, type){

$.notify({
    icon: "add_alert",
    message: msg

},{
    type: type,
    timer: 4000,
    placement: {
        from: 'top',
        align: 'center',
    }
});
}</script>
<!-- code for notifications 
############################################################################################
-->
{% endblock %}

associate/templates/associate/profileEdit.html
{% extends "base.html" %}
{% block title %}
Update My Profile
{% endblock title %}
<!-- heading  -->
{% block heading %}
Update My Profile
{% endblock %}

<!-- desktop menu -->
{% block desk-sidebar%}
{% include 'sidebar.html' %}
{% endblock %}

{% load static %}
<!-- Main Conent -->
{% block content %}

                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% load crispy_forms_tags %}
                    {% load widget_tweaks %}
                 {{form|crispy}}
        <!--     
            photo=models.ImageField(upload_to='images/associate/',blank=True, null=True)
             -->
             <div class="d-flex justify-content-center">
                    <button type="submit" class="btn btn-primary">Submit</button>
             </div>
                
                </form>
            </div>
                </form>

{% endblock %}


{% load static %}

associate/templates/associate/register.html
{% extends "base.html" %}
{% block title %}

{% endblock title %}
<!-- heading  -->
{% block heading %}

{% endblock %}


<!-- desktop menu -->
{% block desk-sidebar%}
{% include 'sidebar.html' %}
{% endblock %}



<!-- Main Conent -->
{% block content %}
{% if error %}
{% url 'associate:home' as home %}
<script>
    window.location.replace('{{home}}');
</script>
{% endif %}
<div class="row ">
    <div class="col-lg-12">
           
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% load crispy_forms_tags %}
            {% load widget_tweaks %}
            Name: {% render_field form.name class="form-control" %} <br>
            Upline Associate ID:
            <!-- <input type="text" class="form-control" name="associate_ref" id="associate_ref"> -->
            <br>
            {% render_field form.upline class="form-control" %} 
            Contact Number:
            {% render_field form.contact_no class="form-control" %} <br>            
            Alternate Number
            {% render_field form.alternate_no class="form-control" %} <br>
            Address
            {% render_field form.address class="form-control" %}
            <input type="hidden" name="user" value="{{user.id}}">
            <input type="hidden" name="email" value="{{user.username}}">
            Upload your Photo:
            {% render_field form.photo class="form-control" %}
<!--     
    photo=models.ImageField(upload_to='images/associate/',blank=True, null=True)
     -->
     <div class="d-flex justify-content-center">
            <button type="submit" class="btn btn-primary">Submit</button>
     </div>
        
        </form>
    </div>

</div>
{% endblock %}


{% load static %}