associate/urls.py
from django.urls import path,include
from . import views

app_name="associate"
urlpatterns = [  
    path('', views.index,name='home'),
   # path('register', views.register, name='register'), 
    path('project', views.projects,name='projects'),
    path('project/<int:id>/', views.projectView, name='project_view'),
    path('project/<int:proid>/section/<int:id>', views.sectionView, name='section_view'), 
    path('property/<int:id>/', views.propertyView,name='property_view'),
    path('project/plc', views.plcRules,name='plcRules'),
    path('customers', views.customerListView, name='customers'),
    path('customers/<int:id>/', views.customerView, name='customer_view'),
    path('rewards', views.rewardView, name='rewards'),
    path('upline', views.uplineView, name='upline'), 
    path('downlines', views.downlines, name='downlines'),
    path('downlines/<int:id>', views.downlineView, name='downline_view'),
    path('downlines/add', views.downlineCreateView, name='downline_add'),    
    path('buisness-summary', views.buisnessSummary, name='buisness_summary'),
    path('team-buisness', views.teamBuisness, name='team_buisness'),
    path('leader-rewards', views.leaderRewards, name='leader_rewards'),
    path('my-earnings', views.myEarnings, name='my_earnings'),
    path('earnings-forcast', views.earningForcast, name='earning_forcast'),
    path('passbook', views.passbook, name='passbook'),
    path('profile', views.myProfile, name='profile'),
    path('profile/edit', views.profileEdit, name='profile_edit'), 
    path('changepwd', views.changePwd, name='changepwd'),              
    ]

    #project/id/edit
    

customers/urls.py
from django.urls import path,include
from . import views

app_name="customers"
urlpatterns = [    
    path('login', views.login, name='login'),
    path('login/loader', views.loader, name='loader'),    
    path('register', views.register,name='register'),
    path('home/<int:id>', views.home,name='home'),    
    #path('', views.home,name='home'),
    
        
    
    
]

owner/urls.py
from django.urls import path,include
from . import views

app_name="owner"
urlpatterns = [  
    path('', views.index,name='home'),
    path('project', views.projects,name='projects'),
    path('project/plc', views.plcRules,name='plcRules'),
    path('project/plc/create', views.plcRulesCreate,name='plcRules_create'),
    path('project/plc/<int:id>/edit', views.plcRulesEdit,name='plcRules_edit'),
    path('project/<int:id>/', views.projectView, name='project_view'),
    path('project/<int:id>/edit', views.projectEdit, name='project_edit'),
    path('project/<int:id>/delete', views.projectDelete, name='project_delete'),
    path('project/<int:proid>/section/<int:id>', views.sectionView, name='section_view'),
    path('project/<int:proid>/section/<int:id>/edit', views.sectionEdit, name='section_edit'),
    path('project/<int:proid>/section/<int:id>/delete', views.sectionDelete, name='section_delete'),
    path('property/<int:id>/', views.propertyView,name='property_view'),
    path('property/<int:id>/edit', views.propertyEdit,name='property_edit'),
    path('property/<int:id>/delete', views.propertyDelete,name='property_delete'),
    path('customers', views.customerListView, name='customers'),
    path('customers/add', views.createCutomer, name='customer_create'),
    path('customers/<int:id>/edit', views.customerEdit, name='customer_edit'),
    path('customers/<int:id>/', views.customerView, name='customer_view'),
    path('associates', views.associates, name='associates'),
    path('associates/add', views.associateCreate, name='associate_view'),
    path('associates/edit/<int:id>', views.associateEdit, name='associate_edit'),
    path('associates/edit/<int:id>/photo', views.associateEditPhoto, name='associate_edit_photo'),
    path('associates/suspend/<int:id>', views.associateSuspend, name='associate_suspend'),
    path('associates/activate/<int:id>', views.associateActivate, name='associate_activate'),
    path('associates/hold-payments/<int:id>', views.associateHoldPayments, name='associate_HoldPayments'),
    path('associates/release-payments/<int:id>', views.associateReleasePayments, name='associate_releasePayments'),
    path('associates/terminate/<int:id>', views.associateTerminate, name='associate_terminate'),
    path('associates/<int:id>', views.associateView, name='associate_view'),
    path('sales/status/',views.propertyByStatus,name='property_status'),
    path('sales/status/list/<slug:slug>',views.propertyListByStatus,name='property_list_status'),
    path('sales/pos/',views.sales,name='pos_list'),
    path('sales/pos/<int:id>',views.pointofSales,name='pos'),
    path('sales/salesbook/',views.salesBook,name='sales_book'),
    path('sales/receipt/<int:id>',views.bookingReceipt,name='booking_receipt'),
    path('finance/booking-deposit/<int:id>', views.depositBooking, name='booking_deposit'),
    path('finance/login-amount', views.loginAmount, name='login_amount'),
    path('finance/deposit-login-amount/<int:id>', views.depositLoginAmount, name='deposit_login_amount'),
    path('finance/deposit-emi/<int:id>', views.depositEmi, name='deposit_emi'),
    path('finance/receipt/<int:id>',views.paymentReceipt,name='payment_receipt'),
    path('finance/payouts', views.payoutList, name='payout_list'),
    path('finance/payouts/advance', views.payoutAdvance, name='payout_advance'),
    path('finance/payout-payments/<int:id>', views.payoutPayment, name='payout_payments'),
    path('finance/release-earnings/<int:id>', views.releaseEarnings, name='release_earning'),
    path('finance/rewards', views.rewards, name='rewards'),
    path('finance/other-expences/<int:id>', views.otherExpences, name='other_expences'),
    path('finance/redeem-rewards/<int:id>', views.redeemRewards, name='redeem_rewards'),
    path('reports/sales-report',views.salesReport, name='sales_report'),
    path('reports/buisness-report',views.buisnessReport, name='buisness_report'),
    path('reports/emi-report',views.emiReport, name='emi_report'),
    path('profile',views.salesBook, name='profile_edit'),
    path('policy/payout/', views.payoutRules, name='payout_rules'),
    path('policy/payout/create', views.payoutRulesCreate, name='payout_rules_create'),
    path('policy/payout/<int:id>/edit', views.payoutRulesEdit, name='payout_rules_edit'),
    path('policy/rewards/', views.rewardRules, name='reward_rules'),     
    path('policy/rewards/create', views.rewardRulesCreate, name='reward_rules_create'),     
    path('policy/rewards/<int:id>/edit', views.rewardRulesEdit, name='reward_rules_edit'),     
    
    ]

    #project/id/edit
    

projects/api/urls.py
from django.urls import path, include

from . import views
from projects.api.views import PropertyAPIView
from django.conf.urls import url
from rest_framework import routers

urlpatterns = [
    #path('rud/<int:id>', CustomerRudView.as_view()),     
    path('property/get/<int:section_id>', PropertyAPIView.as_view()),
   # path('post/', CustomerCreateApiView.as_view()),
    
]

projects/urls.py
from django.urls import path,include
from . import views


app_name="project"
urlpatterns = [  
    
    path('<int:id>', views.project_profile, name='project_profile'),
    path('availability/<int:id>', views.availability, name='availability'),
    path('booking/project/<int:id>/',views.booking, name='booking'),
    path('', views.project, name='home'),  
    #path('test', views.test),
    
    
]

realEstate2/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings 
from django.conf.urls.static import static 


urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('webapp.urls')),
    path('associate/' , include('associate.urls')),
    path('customers/' , include('customers.urls')),
    path('owner/' , include('owner.urls')),
    path('projects/' , include('projects.urls')),
    path('api/customer/' , include('customers.api.urls')),
    path('api/config/' , include('config.api.urls')),
    #path('api/project/' , include('projects.api.urls')),
    path('user/' , include('user.urls'))
    #path('report/' , include('reports.urls'))
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path,include
from . import views

app_name="user"
urlpatterns = [  
    
    path('login', views.login ,name='login'),
   # path('register', views.register ,name='register'),
   # path('forgot-password', views.forgotPassword ,name='forgot'),
    path('logout', views.logout ,name='logout'),
    path('password-change',views.passwordChange ,name='passwordChange'),
    path('profile-edit',views.profileEdit ,name='profile_edit'),
    path('profile-view',views.profileView ,name='profile_view'),
    path('user-list',views.userList,name='user_list'),
    path('add-user',views.addUser,name='add_user'),
    path('activate-user/<int:id>',views.userActivate,name='activate_user'),
    path('deactivate-user/<int:id>',views.userDeactivate,name='deactivate_user'),

     
    ]

    #project/id/edit
    

projects/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime, timedelta
from customers.models import Customer

class Project(models.Model):
    CATEGORY = (             
        ('R', 'Residential'),
        ('C', 'Commercial'),        
    )
    name= models.CharField(max_length=100)
    category=models.CharField(max_length=1, choices=CATEGORY)
    address= models.TextField(blank=True, null=True)
    pin_code=models.IntegerField(blank=True, null=True)
    description= models.TextField(blank=True, null=True)
    city=models.CharField(max_length=100,blank=True, null=True)
    locality=models.CharField(max_length=100)
    is_active=models.BooleanField(blank=True, null=True)
    geo_code_lat=models.DecimalField(max_digits=10, decimal_places=6,blank=True, null=True)
    geo_code_long=models.DecimalField(max_digits=10, decimal_places=6,blank=True, null=True)
    cover_image=models.ImageField(upload_to='images/project/',blank=True, null=True)
    layout= models.FileField(upload_to='files/project/',blank=True, null=True)
    createdAt= models.DateTimeField(auto_now=True) 
    updatedAt= models.DateTimeField(auto_now_add=True)   

class Section(models.Model):
    #REduntant possible future use
    TYPE = (             
        ('L', 'Land'),
        ('A', 'Apartment'),
        ('V', 'Villa'),
        ('S', 'Shop'),
        
    )
    name=models.CharField(max_length=50)
    project_ref= models.ForeignKey(Project, on_delete=models.CASCADE)
    section_prefix=models.CharField(max_length=4)
    dimensions=models.CharField(max_length=50)
    area=models.IntegerField()
    cost_per_unit=models.IntegerField()

    class Meta:
        verbose_name = "Section"
        verbose_name_plural = "Sections"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("Section_detail", kwargs={"pk": self.pk})

class PriceRule(models.Model):
    name=models.CharField(max_length=50)
    premium_price=models.IntegerField()   

class Property(models.Model):
    STATUS = (             
        ('V', 'Vacant'),
        ('H', 'Hold'),
        ('B', 'Booked'),
        ('A', 'Alloted'),
        ('R', 'Registered'),        
    )
    EMI_PLAN = (
      (0, 'Full Payment'),
      (1, '1 Year Plan'),
      (2, '2 Year Plan'),
      (3, '3 Year Plan'),
    )
    emi_plan = models.PositiveSmallIntegerField(choices=EMI_PLAN,blank=True, null=True)
    serial_no= models.IntegerField()
    status_code=models.CharField(max_length=1, choices=STATUS)
    customer_ref=models.ForeignKey(Customer, on_delete=models.CASCADE, blank=True, null=True)
    section_ref= models.ForeignKey(Section, on_delete=models.CASCADE)
    price_rule=models.ForeignKey(PriceRule, on_delete=models.CASCADE)
    class Meta:
        verbose_name = "Property"
        verbose_name_plural = "Properties"  

    def get_absolute_url(self):
        return reverse("Property_detail", kwargs={"pk": self.pk})

class TempBooking(models.Model):
    property_ref=models.ForeignKey(Property, on_delete=models.CASCADE)
    customer_ref=models.ForeignKey(Customer, on_delete=models.CASCADE)
    booking_date=models.DateTimeField()
    booking_revoke_date=models.DateTimeField()
    status= models.BooleanField(default=True)
    
    class Meta:
        verbose_name = ("tempBooking")
        verbose_name_plural = ("tempBookings")
    def get_absolute_url(self):
        return reverse("tempBooking_detail", kwargs={"pk": self.pk})
class EMI(models.Model):
    property_ref=models.ForeignKey(Property, on_delete=models.CASCADE)
    pay_day=models.DateField(blank=True,auto_now=False, auto_now_add=False)
    opening_balance=models.DecimalField(blank=True,null=True, max_digits=20, decimal_places=2)
    emi=models.DecimalField(blank=True,null=True, max_digits=20, decimal_places=2)
    intrest_paid=models.DecimalField(blank=True,null=True, max_digits=20, decimal_places=2)
    closing_balance=models.DecimalField(blank=True,null=True, max_digits=20, decimal_places=2)
    status= models.BooleanField(default=False)
    class Meta:
        verbose_name = ("emi")
        verbose_name_plural = ("emis") 

    def get_absolute_url(self):
        return reverse("emi_detail", kwargs={"pk": self.pk})
class Transaction(models.Model):
    METHOD = (
             
        ('C', 'Cash Payment'),
        ('Q', 'Cheque'),
        ('N', 'NEFT'),
        ('D', 'Bank Draft'),
        ('A', 'Asscociate Credit'),
        
    )
    #customer_ref= models.ForeignKey(Customer, on_delete=models.CASCADE)
    pay_method=models.CharField(max_length=1, choices=METHOD)
    property_ref=models.ForeignKey(Property, on_delete=None,blank=True,null=True)
    sale_value=models.DecimalField( max_digits=20, decimal_places=2,blank=True,null=True)
    date=models.DateTimeField(blank=True,auto_now=False, auto_now_add=True)
    reference_no=models.CharField(blank=True,null=True, max_length=50)
    credit=models.DecimalField( max_digits=20, decimal_places=2,blank=True,null=True)
    debit=models.DecimalField( max_digits=20, decimal_places=2,blank=True,null=True)
    balance=models.DecimalField( max_digits=20, decimal_places=2,blank=True,null=True)
    description=models.TextField(blank=True,null=True)

    class Meta:
        verbose_name = ("Transaction")
        verbose_name_plural = ("Transactions")
    def get_absolute_url(self):
        return reverse("Transactions_detail", kwargs={"pk": self.pk})
######################################
#Depriciated
#########################################
""" class NearByPlace(models.Model):
    place_name=models.CharField(max_length=50)
    place_icon=models.CharField(max_length=50)    
    members = models.ManyToManyField(Project, through='Project_nearPlace')
class Project_nearPlace(models.Model):
  #  date_joined = models.DateField()  
    projectref = models.ForeignKey(Project, on_delete=models.CASCADE)
    places = models.ForeignKey(NearByPlace, on_delete=models.CASCADE)
    dist= models.CharField(max_length=50)
    is_allowed=models.BooleanField() 
class Amenity(models.Model):
    amenity_name=models.CharField(max_length=50)
    amenity_icon=models.CharField(max_length=50)    
    members = models.ManyToManyField(Project, through='Project_amenity')
class Project_amenity(models.Model):
  #  date_joined = models.DateField()  
    projectref = models.ForeignKey(Project, on_delete=models.CASCADE)
    amenities = models.ForeignKey(Amenity, on_delete=models.CASCADE)
    is_allowed=models.BooleanField()         

class Images(models.Model):
    #imageID
    #entityID
    proref = models.ForeignKey(Project, on_delete=models.CASCADE)
    image_path= models.URLField()
    is_video = models.BooleanField(default=False)
    full_video_path= models.URLField(default='')
    class Meta:
        verbose_name = "Project Image"
        verbose_name_plural = "Project Images" 
########################################## """ 

projects/api/views.py
from rest_framework import viewsets,status,generics
from rest_framework.views import APIView
from rest_framework.response import Response
from customers.api.serializers import CustomerSerializer
from customers.models import Customer
from projects.models import Property,PriceRule
from projects.api.serializers import PropertySerializer 



class PropertyAPIView(APIView):
    def get(self, request,section_id):
        queryset= Property.objects.all().filter(section_id=section_id)
        serializer_context = {
            'request': request,
        }
     
        serializer= PropertySerializer(instance=queryset,context=serializer_context, many=True)
        return Response(serializer.data, headers={'Access-Control-Allow-Origin': '*'})

class CustomerRudView(generics.RetrieveUpdateDestroyAPIView):
  lookup_field=  'id'
  serializer_class= CustomerSerializer
  def get_queryset(self):    
    queryset = Customer.objects.all() # TODO
    return queryset
  #def get_object(self):
  #,'section_id','price_rule'
    #contact_no=self.kwargs.get('contact_no')
    #return Customer.objects.get(contact_no=contact_no)

class CustomerCreateApiView(generics.CreateAPIView):
    lookup_field= 'pk'
    serializer_class= CustomerSerializer    
    def get_queryset(self):        
        queryset= Customer.objects.all()
        return queryset

projects/templates/projects/admin_sectionView.html
{% extends "base.html" %}
{% block title %}
{{project.name}} Project
{% endblock title %}
<!-- heading  -->
{% block heading %}
{{project.name}} Project - {{section.name}}
{% endblock %}


<!-- desktop menu -->
{% block desk-sidebar%}
{% include 'sidebar.html' %}
{% endblock %}

<!-- Main Conent -->
{% load static %}
{% block content %}
<div class="row m-t-25">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header" style="background-image: url('{% get_media_prefix %}{{project.cover_image}}');
                                  background-position: center;
                                  background-size: cover;
                                  height: 300px;
                          ">
                <div class="bg-dark">

                </div>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-auto">

                    </div>
                </div>
                <table class="table">
                    <tbody>
                        <tr>
                            <th scope="row">Section ID</th>
                            <td>{{section.id}}</td>
                        </tr>
                        <tr>
                            <th scope="row">Dimentions</th>
                            <td>{{section.dimensions}} in Ft</td>
                        </tr>
                        <tr>
                            <th scope="row">Area</th>
                            <td>{{section.area}} sq. ft </td>
                        </tr>
                        <tr>
                            <th scope="row">Cost</th>
                            <td>&#8377; {{section.cost_per_unit}} per sq ft</td>
                        </tr>

                    </tbody>
                </table>
                <div class="p-3 d-flex justify-content-center ">

                    {% if user.user_type == 1 or user.user_type == 2 %}
                    <button type="button" class="btn btn-sm btn-primary m-1" data-toggle="modal"
                        data-target="#exampleModal">
                        <i class="fas fa-plus-circle"></i>
                        Add Properties
                    </button>
                    <a class="btn btn-warning btn-sm float-left m-1"
                        href="{% url 'owner:section_edit' proid=section.project_ref.id id=section.id %}">
                        <i class="far fa-edit"></i>
                        Edit </a>
                    {% endif %}
                    {% if user.user_type == 1 %}
                    <button class="btn btn-sm m-1 float-right btn-danger" onclick="del()">
                        <i class="far fa-trash-alt"></i>
                        Delete
                    </button>

                    {% endif %}



                </div>

                <script>
                    function del() {
                        swal({
                            title: "Are you sure?",
                            text: "You wont be able to revert this!",
                            type: "warning",
                            showCancelButton: true,
                            confirmButtonColor: "#00C851",
                            cancelButtonColor: "#d33",
                            confirmButtonText: "Yes, delete it!",
                            confirmButtonClass: "btn btn-success"
                        }).then((result) => {
                            if (result.value) {
                                Swal.fire(
                                    'Deleted!',
                                    'Your file has been deleted.',
                                    'success'
                                )
                                window.location = "{% url 'owner:section_delete' id=section.id proid=section.project_ref.id %}";
                            }
                        })
                            ;

                    }
                </script>
                <hr>
                <div class="table-responsive ml-2 mr-2">
                    <table class=" myTable table table-striped ">
                        <thead>
                            <tr>
                                <th>Serial No.</th>
                                <th>Price Rule</th>
                                <th>Cost per Unit</th>
                                <th>Status</th>
                                <th>Customer Name</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% load mathfilters %}
                            {% for property in properties %}

                            {% if property.section_ref.id == section.id %}

                            <tr>
                                <td data-order="{{property.serial_no}}">{{section.section_prefix}}-{{property.serial_no}} </td>
                                <td>{{property.price_rule.name}}</td>
                                <td>

                                    {% with cost=section.cost_per_unit factor=property.price_rule.premium_price|add:100|div:100 %}
                                    &#8377; {{cost|mul:factor}}</td>
                                {% endwith %}
                                <td>
                                    {% if property.status_code == "V"  %}
                                    <span class="badge  badge-pill badge-success">Vacant</span>
                                    {% elif property.status_code == "H" %}
                                    <span class="badge badge-pill badge-warning">Hold</span>
                                    {% elif property.status_code == "B" %}
                                    <span class="badge badge-pill badge-danger">Booked</span>
                                    {% elif property.status_code == "A" %}
                                    <span class="badge badge-pill badge-primary">Alloted</span>
                                    {% else  %}
                                    <span class="badge badge-pill badge-secondary">Registered</span>

                                    {% endif %}
                                    <!--  -->
                                </td>
                                <td> {% if property.customer_ref %}
                                    {% if property.customer_ref.associate_ref_id == associate.id and user.user_type == 7%}
                                    <a href="{% url 'associate:customer_view' id=property.customer_ref_id %}">
                                        {{property.customer_ref.name}}</a>
                                    {% elif  user.user_type == 7 %}
                                    {{property.customer_ref.name}}
                                    {% else %}
                                    <a href="{% url 'owner:customer_view' id=property.customer_ref_id %}">{{property.customer_ref.name}}</a>
                                    {% endif %}
                                    {% else %}
                                    <span class="text-danger" style="font-weight: 500; font-size: 9pt;">NONE</span>
                                    {% endif %}</td>
                                <td>

                                    {% if user.user_type == 1 or user.user_type == 2 %}
                                    <a class="btn btn-sm  btn-info"
                                        href="{% url 'owner:property_view' id=property.id %} ">
                                        <i class="far fa-eye"></i>
                                    </a>

                                    <a class="btn btn-sm  btn-warning"
                                        href="{% url 'owner:property_edit' id=property.id %} ">
                                        <i class="far fa-edit"></i>
                                    </a>

                                    {% if user.user_type == 1 %}
                                    <a class="btn btn-sm  btn-danger"
                                        href="{% url 'owner:property_delete' id=property.id %}">
                                        <i class="far fa-trash-alt"></i>
                                        {% endif %}



                                        {% elif user.user_type == 7%}
                                        <a class="btn btn-sm  btn-info"
                                            href="{% url 'associate:property_view' id=property.id %} ">
                                            <i class="far fa-eye"></i>
                                        </a>
                                        {% else %}
                                        <a class="btn btn-sm  btn-info"
                                            href="{% url 'owner:property_view' id=property.id %} ">
                                            <i class="far fa-eye"></i>
                                        </a>

                                        {% endif %}


                                </td>

                            </tr>
                            {% endif %}
                            {% endfor %}

                        </tbody>
                    </table>
                    <script>
                        $(document).ready(function () {
                            $('.myTable').DataTable();
                        });
                    </script>


                </div>


            </div>
        </div>
    </div>


</div>
{% endblock %}
{% block modal %}
<!-- Modals Start -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Add Property</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="" method="post">
                    {% csrf_token %}
                    {% load crispy_forms_tags %}
                    <!--  {{form|crispy}} -->
                    <div class="form-row">
                        <div class="form-group col-auto mb-0">
                            {{ form.serial_no|as_crispy_field }}
                            <span class="form-text text-muted" style="font-size: 10pt;
                font-weight: 500;
                text-transform: capitalize;
                ">
                                Example: 1,2 3
                            </span>
                        </div>

                        <input type="hidden" name="section_ref" value="{{section.id}}">
                    </div>
                    <div class="form-row">
                        <div class="form-group col-auto mb-0">
                            {{ form.status_code|as_crispy_field }}
                            <span class="form-text text-muted" style="font-size: 10pt;
                font-weight: 500;
                text-transform: capitalize;
                ">
                                Example: vacant
                            </span>
                        </div>
                        <div class="form-group col-auto mb-0">
                            {{ form.customer_ref|as_crispy_field }}
                            <span class="form-text text-muted" style="font-size: 10pt;
            font-weight: 500;
            text-transform: capitalize;
            ">
                                Example: Customer id-1
                            </span>
                        </div>

                    </div>
                    <div class="form-row">
                        <div class="form-group col-auto mb-0">
                            {{ form.price_rule|as_crispy_field }}
                            <span class="form-text text-muted" style="font-size: 10pt;
                font-weight: 500;
                text-transform: capitalize;
                ">
                                {% for price in price_rules %}
                                Rule {{price.id}} : {{price.name}} at {{price.premium_price}}% premium <br>
                                {% endfor %}
                            </span>
                        </div>
                    </div>


            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Save</button>
            </div>

            </form>
        </div>

    </div>
</div>
{% endblock %}